name: Cypress tests for CI/CD
on: [push, workflow_dispatch]
env:
  CYPRESS_USERNAME: ${{ secrets.USERNAME }} 
  CYPRESS_PASSWORD: ${{ secrets.PASSWORD }} 
  
jobs:
 print-envs:
    name: Print environment variables
    runs-on: ubuntu-latest
    
    steps:
      - name: Print environment variables
        run: |
          echo CYPRESS_USERNAME: $CYPRESS_USERNAME
          echo CYPRESS_PASSWORD: $CYPRESS_PASSWORD
          
 cypress-run:
    runs-on: ubuntu-latest
    steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Npm Updates
           run: npm install
           
         - name: Cypress run
           uses: cypress-io/github-action@v6
           with:
             start: npx cypress run --headless
             browser: chrome
               
