name: Cypress tests for CI/CD
on: [push, workflow_dispatch]
env:
  CYPRESS_USERNAME: ${{ secrets.USERNAME }} 
  CYPRESS_PASSWORD: ${{ secrets.PASSWORD }} 
  
jobs:     
 cypress-run:
    runs-on: ubuntu-latest
    steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Npm Updates
           run: npm install
           
         - name: Cypress run
           uses: cypress-io/github-action@v6
           with:
             start: npx cypress run --headless
             browser: chrome
               
