name: Cypress tests for CI/CD
on: [push]
jobs:
 cypress-run:
    runs-on: ubuntu-latest
    steps:
         - name: Checkout
           uses: actions/checkout@v3
           
         - name: Cypress run
           env:
             username: ${{ secrets.CYPRESS_USERNAME}} 
             password: ${{ secrets.CYPRESS_PASSWORD}} 
           uses: cypress-io/github-action@v6
           with:
             start: CYPRESS_USERNAME=$username CYPRESS_PASSWORD=$password npx cypress run 
             browser: chrome
               
